set folder="C:\Users\Fernan\Documents\contractor-net\Dependencies\CCI-AST"

xcopy /y  .\CodeGenerators\ControlAndDataFlowGraph\bin\Debug\CodeContracts\Microsoft.Cci.Analysis.ControlAndDataFlowGraph.Contracts.dll %folder%
xcopy /y  .\CodeGenerators\ControlAndDataFlowGraph\bin\Debug\CodeContracts\Microsoft.Cci.Analysis.ControlAndDataFlowGraph.Contracts.pdb %folder%
xcopy /y  .\CodeGenerators\ControlAndDataFlowGraph\bin\Debug\Microsoft.Cci.Analysis.ControlAndDataFlowGraph.dll %folder%
xcopy /y  .\CodeGenerators\ControlAndDataFlowGraph\bin\Debug\Microsoft.Cci.Analysis.ControlAndDataFlowGraph.pdb %folder%
xcopy /y  .\CodeGenerators\ControlAndDataFlowGraph\bin\Debug\Microsoft.Cci.MetadataHelper.dll %folder%
xcopy /y  .\CodeGenerators\ControlAndDataFlowGraph\bin\Debug\Microsoft.Cci.MetadataHelper.pdb %folder%
xcopy /y  .\CodeGenerators\ControlAndDataFlowGraph\bin\Debug\Microsoft.Cci.MetadataModel.dll %folder%
xcopy /y  .\CodeGenerators\ControlAndDataFlowGraph\bin\Debug\Microsoft.Cci.MetadataModel.pdb %folder%
xcopy /y  .\CodeGenerators\ControlAndDataFlowGraph\bin\Debug\Microsoft.Cci.SourceModel.dll %folder%
xcopy /y  .\CodeGenerators\ControlAndDataFlowGraph\bin\Debug\Microsoft.Cci.SourceModel.pdb %folder%
xcopy /y  .\CodeGenerators\Optimization\bin\Debug\CodeContracts\Microsoft.Cci.Optimization.OptimizationUtilities.Contracts.dll %folder%
xcopy /y  .\CodeGenerators\Optimization\bin\Debug\CodeContracts\Microsoft.Cci.Optimization.OptimizationUtilities.Contracts.pdb %folder%
xcopy /y  .\CodeGenerators\Optimization\bin\Debug\Microsoft.Cci.Analysis.AnalysisUtilities.dll %folder%
xcopy /y  .\CodeGenerators\Optimization\bin\Debug\Microsoft.Cci.Analysis.AnalysisUtilities.pdb %folder%
xcopy /y  .\CodeGenerators\Optimization\bin\Debug\Microsoft.Cci.Analysis.ControlAndDataFlowGraph.dll %folder%
xcopy /y  .\CodeGenerators\Optimization\bin\Debug\Microsoft.Cci.Analysis.ControlAndDataFlowGraph.pdb %folder%
xcopy /y  .\CodeGenerators\Optimization\bin\Debug\Microsoft.Cci.ILGenerator.dll %folder%
xcopy /y  .\CodeGenerators\Optimization\bin\Debug\Microsoft.Cci.ILGenerator.pdb %folder%
xcopy /y  .\CodeGenerators\Optimization\bin\Debug\Microsoft.Cci.MetadataHelper.dll %folder%
xcopy /y  .\CodeGenerators\Optimization\bin\Debug\Microsoft.Cci.MetadataHelper.pdb %folder%
xcopy /y  .\CodeGenerators\Optimization\bin\Debug\Microsoft.Cci.MetadataModel.dll %folder%
xcopy /y  .\CodeGenerators\Optimization\bin\Debug\Microsoft.Cci.MetadataModel.pdb %folder%
xcopy /y  .\CodeGenerators\Optimization\bin\Debug\Microsoft.Cci.MutableMetadataModel.dll %folder%
xcopy /y  .\CodeGenerators\Optimization\bin\Debug\Microsoft.Cci.MutableMetadataModel.pdb %folder%
xcopy /y  .\CodeGenerators\Optimization\bin\Debug\Microsoft.Cci.Optimization.OptimizationUtilities.dll %folder%
xcopy /y  .\CodeGenerators\Optimization\bin\Debug\Microsoft.Cci.Optimization.OptimizationUtilities.pdb %folder%
xcopy /y  .\CodeGenerators\Optimization\bin\Debug\Microsoft.Cci.SourceModel.dll %folder%
xcopy /y  .\CodeGenerators\Optimization\bin\Debug\Microsoft.Cci.SourceModel.pdb %folder%
xcopy /y  .\CodeGenerators\OptimizationUtilities\bin\Debug\CodeContracts\Microsoft.Cci.Analysis.AnalysisUtilities.Contracts.dll %folder%
xcopy /y  .\CodeGenerators\OptimizationUtilities\bin\Debug\CodeContracts\Microsoft.Cci.Analysis.AnalysisUtilities.Contracts.pdb %folder%
xcopy /y  .\CodeGenerators\OptimizationUtilities\bin\Debug\Microsoft.Cci.Analysis.AnalysisUtilities.dll %folder%
xcopy /y  .\CodeGenerators\OptimizationUtilities\bin\Debug\Microsoft.Cci.Analysis.AnalysisUtilities.pdb %folder%
xcopy /y  .\CodeGenerators\OptimizationUtilities\bin\Debug\Microsoft.Cci.Analysis.ControlAndDataFlowGraph.dll %folder%
xcopy /y  .\CodeGenerators\OptimizationUtilities\bin\Debug\Microsoft.Cci.Analysis.ControlAndDataFlowGraph.pdb %folder%
xcopy /y  .\CodeGenerators\OptimizationUtilities\bin\Debug\Microsoft.Cci.MetadataHelper.dll %folder%
xcopy /y  .\CodeGenerators\OptimizationUtilities\bin\Debug\Microsoft.Cci.MetadataHelper.pdb %folder%
xcopy /y  .\CodeGenerators\OptimizationUtilities\bin\Debug\Microsoft.Cci.MetadataModel.dll %folder%
xcopy /y  .\CodeGenerators\OptimizationUtilities\bin\Debug\Microsoft.Cci.MetadataModel.pdb %folder%
xcopy /y  .\CodeGenerators\OptimizationUtilities\bin\Debug\Microsoft.Cci.MutableMetadataModel.dll %folder%
xcopy /y  .\CodeGenerators\OptimizationUtilities\bin\Debug\Microsoft.Cci.MutableMetadataModel.pdb %folder%
xcopy /y  .\CodeGenerators\OptimizationUtilities\bin\Debug\Microsoft.Cci.SourceModel.dll %folder%
xcopy /y  .\CodeGenerators\OptimizationUtilities\bin\Debug\Microsoft.Cci.SourceModel.pdb %folder%
xcopy /y  .\Converters\CodeModelToIL\bin\Debug\CodeContracts\Microsoft.Cci.CodeModelToIL.Contracts.dll %folder%
xcopy /y  .\Converters\CodeModelToIL\bin\Debug\CodeContracts\Microsoft.Cci.CodeModelToIL.Contracts.pdb %folder%
xcopy /y  .\Converters\CodeModelToIL\bin\Debug\Microsoft.Cci.CodeModel.dll %folder%
xcopy /y  .\Converters\CodeModelToIL\bin\Debug\Microsoft.Cci.CodeModel.pdb %folder%
xcopy /y  .\Converters\CodeModelToIL\bin\Debug\Microsoft.Cci.CodeModelToIL.dll %folder%
xcopy /y  .\Converters\CodeModelToIL\bin\Debug\Microsoft.Cci.CodeModelToIL.pdb %folder%
xcopy /y  .\Converters\CodeModelToIL\bin\Debug\Microsoft.Cci.ILGenerator.dll %folder%
xcopy /y  .\Converters\CodeModelToIL\bin\Debug\Microsoft.Cci.ILGenerator.pdb %folder%
xcopy /y  .\Converters\CodeModelToIL\bin\Debug\Microsoft.Cci.MetadataHelper.dll %folder%
xcopy /y  .\Converters\CodeModelToIL\bin\Debug\Microsoft.Cci.MetadataHelper.pdb %folder%
xcopy /y  .\Converters\CodeModelToIL\bin\Debug\Microsoft.Cci.MetadataModel.dll %folder%
xcopy /y  .\Converters\CodeModelToIL\bin\Debug\Microsoft.Cci.MetadataModel.pdb %folder%
xcopy /y  .\Converters\CodeModelToIL\bin\Debug\Microsoft.Cci.SourceModel.dll %folder%
xcopy /y  .\Converters\CodeModelToIL\bin\Debug\Microsoft.Cci.SourceModel.pdb %folder%
xcopy /y  .\Converters\ContractExtractor\bin\Debug\CodeContracts\Microsoft.Cci.ContractExtractor.Contracts.dll %folder%
xcopy /y  .\Converters\ContractExtractor\bin\Debug\CodeContracts\Microsoft.Cci.ContractExtractor.Contracts.pdb %folder%
xcopy /y  .\Converters\ContractExtractor\bin\Debug\Microsoft.Cci.Analysis.ControlAndDataFlowGraph.dll %folder%
xcopy /y  .\Converters\ContractExtractor\bin\Debug\Microsoft.Cci.Analysis.ControlAndDataFlowGraph.pdb %folder%
xcopy /y  .\Converters\ContractExtractor\bin\Debug\Microsoft.Cci.CodeModel.dll %folder%
xcopy /y  .\Converters\ContractExtractor\bin\Debug\Microsoft.Cci.CodeModel.pdb %folder%
xcopy /y  .\Converters\ContractExtractor\bin\Debug\Microsoft.Cci.CodeModelToIL.dll %folder%
xcopy /y  .\Converters\ContractExtractor\bin\Debug\Microsoft.Cci.CodeModelToIL.pdb %folder%
xcopy /y  .\Converters\ContractExtractor\bin\Debug\Microsoft.Cci.ContractExtractor.dll %folder%
xcopy /y  .\Converters\ContractExtractor\bin\Debug\Microsoft.Cci.ContractExtractor.pdb %folder%
xcopy /y  .\Converters\ContractExtractor\bin\Debug\Microsoft.Cci.ILGenerator.dll %folder%
xcopy /y  .\Converters\ContractExtractor\bin\Debug\Microsoft.Cci.ILGenerator.pdb %folder%
xcopy /y  .\Converters\ContractExtractor\bin\Debug\Microsoft.Cci.MetadataHelper.dll %folder%
xcopy /y  .\Converters\ContractExtractor\bin\Debug\Microsoft.Cci.MetadataHelper.pdb %folder%
xcopy /y  .\Converters\ContractExtractor\bin\Debug\Microsoft.Cci.MetadataModel.dll %folder%
xcopy /y  .\Converters\ContractExtractor\bin\Debug\Microsoft.Cci.MetadataModel.pdb %folder%
xcopy /y  .\Converters\ContractExtractor\bin\Debug\Microsoft.Cci.MutableCodeModel.dll %folder%
xcopy /y  .\Converters\ContractExtractor\bin\Debug\Microsoft.Cci.MutableCodeModel.pdb %folder%
xcopy /y  .\Converters\ContractExtractor\bin\Debug\Microsoft.Cci.MutableMetadataModel.dll %folder%
xcopy /y  .\Converters\ContractExtractor\bin\Debug\Microsoft.Cci.MutableMetadataModel.pdb %folder%
xcopy /y  .\Converters\ContractExtractor\bin\Debug\Microsoft.Cci.NewILToCodeModel.dll %folder%
xcopy /y  .\Converters\ContractExtractor\bin\Debug\Microsoft.Cci.NewILToCodeModel.pdb %folder%
xcopy /y  .\Converters\ContractExtractor\bin\Debug\Microsoft.Cci.pdb %folder%Reader.dll %folder%
xcopy /y  .\Converters\ContractExtractor\bin\Debug\Microsoft.Cci.pdb %folder%Reader.pdb %folder%
xcopy /y  .\Converters\ContractExtractor\bin\Debug\Microsoft.Cci.PeReader.dll %folder%
xcopy /y  .\Converters\ContractExtractor\bin\Debug\Microsoft.Cci.PeReader.pdb %folder%
xcopy /y  .\Converters\ContractExtractor\bin\Debug\Microsoft.Cci.SourceModel.dll %folder%
xcopy /y  .\Converters\ContractExtractor\bin\Debug\Microsoft.Cci.SourceModel.pdb %folder%
xcopy /y  .\Converters\ILGenerator\bin\Debug\CodeContracts\Microsoft.Cci.ILGenerator.Contracts.dll %folder%
xcopy /y  .\Converters\ILGenerator\bin\Debug\CodeContracts\Microsoft.Cci.ILGenerator.Contracts.pdb %folder%
xcopy /y  .\Converters\ILGenerator\bin\Debug\Microsoft.Cci.ILGenerator.dll %folder%
xcopy /y  .\Converters\ILGenerator\bin\Debug\Microsoft.Cci.ILGenerator.pdb %folder%
xcopy /y  .\Converters\ILGenerator\bin\Debug\Microsoft.Cci.MetadataHelper.dll %folder%
xcopy /y  .\Converters\ILGenerator\bin\Debug\Microsoft.Cci.MetadataHelper.pdb %folder%
xcopy /y  .\Converters\ILGenerator\bin\Debug\Microsoft.Cci.MetadataModel.dll %folder%
xcopy /y  .\Converters\ILGenerator\bin\Debug\Microsoft.Cci.MetadataModel.pdb %folder%
xcopy /y  .\Converters\ILGenerator\bin\Debug\Microsoft.Cci.SourceModel.dll %folder%
xcopy /y  .\Converters\ILGenerator\bin\Debug\Microsoft.Cci.SourceModel.pdb %folder%
xcopy /y  .\Converters\NewILToCodeModel\bin\Debug\CodeContracts\Microsoft.Cci.NewILToCodeModel.Contracts.dll %folder%
xcopy /y  .\Converters\NewILToCodeModel\bin\Debug\CodeContracts\Microsoft.Cci.NewILToCodeModel.Contracts.pdb %folder%
xcopy /y  .\Converters\NewILToCodeModel\bin\Debug\Microsoft.Cci.Analysis.ControlAndDataFlowGraph.dll %folder%
xcopy /y  .\Converters\NewILToCodeModel\bin\Debug\Microsoft.Cci.Analysis.ControlAndDataFlowGraph.pdb %folder%
xcopy /y  .\Converters\NewILToCodeModel\bin\Debug\Microsoft.Cci.CodeModel.dll %folder%
xcopy /y  .\Converters\NewILToCodeModel\bin\Debug\Microsoft.Cci.CodeModel.pdb %folder%
xcopy /y  .\Converters\NewILToCodeModel\bin\Debug\Microsoft.Cci.CodeModelToIL.dll %folder%
xcopy /y  .\Converters\NewILToCodeModel\bin\Debug\Microsoft.Cci.CodeModelToIL.pdb %folder%
xcopy /y  .\Converters\NewILToCodeModel\bin\Debug\Microsoft.Cci.ILGenerator.dll %folder%
xcopy /y  .\Converters\NewILToCodeModel\bin\Debug\Microsoft.Cci.ILGenerator.pdb %folder%
xcopy /y  .\Converters\NewILToCodeModel\bin\Debug\Microsoft.Cci.MetadataHelper.dll %folder%
xcopy /y  .\Converters\NewILToCodeModel\bin\Debug\Microsoft.Cci.MetadataHelper.pdb %folder%
xcopy /y  .\Converters\NewILToCodeModel\bin\Debug\Microsoft.Cci.MetadataModel.dll %folder%
xcopy /y  .\Converters\NewILToCodeModel\bin\Debug\Microsoft.Cci.MetadataModel.pdb %folder%
xcopy /y  .\Converters\NewILToCodeModel\bin\Debug\Microsoft.Cci.MutableCodeModel.dll %folder%
xcopy /y  .\Converters\NewILToCodeModel\bin\Debug\Microsoft.Cci.MutableCodeModel.pdb %folder%
xcopy /y  .\Converters\NewILToCodeModel\bin\Debug\Microsoft.Cci.MutableMetadataModel.dll %folder%
xcopy /y  .\Converters\NewILToCodeModel\bin\Debug\Microsoft.Cci.MutableMetadataModel.pdb %folder%
xcopy /y  .\Converters\NewILToCodeModel\bin\Debug\Microsoft.Cci.NewILToCodeModel.dll %folder%
xcopy /y  .\Converters\NewILToCodeModel\bin\Debug\Microsoft.Cci.NewILToCodeModel.pdb %folder%
xcopy /y  .\Converters\NewILToCodeModel\bin\Debug\Microsoft.Cci.pdb %folder%Reader.dll %folder%
xcopy /y  .\Converters\NewILToCodeModel\bin\Debug\Microsoft.Cci.pdb %folder%Reader.pdb %folder%
xcopy /y  .\Converters\NewILToCodeModel\bin\Debug\Microsoft.Cci.PeReader.dll %folder%
xcopy /y  .\Converters\NewILToCodeModel\bin\Debug\Microsoft.Cci.PeReader.pdb %folder%
xcopy /y  .\Converters\NewILToCodeModel\bin\Debug\Microsoft.Cci.SourceModel.dll %folder%
xcopy /y  .\Converters\NewILToCodeModel\bin\Debug\Microsoft.Cci.SourceModel.pdb %folder%
xcopy /y  .\Converters\ReflectionEmitter\bin\Debug\CodeContracts\Microsoft.Cci.ReflectionEmitter.Contracts.dll %folder%
xcopy /y  .\Converters\ReflectionEmitter\bin\Debug\CodeContracts\Microsoft.Cci.ReflectionEmitter.Contracts.pdb %folder%
xcopy /y  .\Converters\ReflectionEmitter\bin\Debug\Microsoft.Cci.MetadataHelper.dll %folder%
xcopy /y  .\Converters\ReflectionEmitter\bin\Debug\Microsoft.Cci.MetadataHelper.pdb %folder%
xcopy /y  .\Converters\ReflectionEmitter\bin\Debug\Microsoft.Cci.MetadataModel.dll %folder%
xcopy /y  .\Converters\ReflectionEmitter\bin\Debug\Microsoft.Cci.MetadataModel.pdb %folder%
xcopy /y  .\Converters\ReflectionEmitter\bin\Debug\Microsoft.Cci.ReflectionEmitter.dll %folder%
xcopy /y  .\Converters\ReflectionEmitter\bin\Debug\Microsoft.Cci.ReflectionEmitter.pdb %folder%
xcopy /y  .\Converters\ReflectionEmitter\bin\Debug\Microsoft.Cci.SourceModel.dll %folder%
xcopy /y  .\Converters\ReflectionEmitter\bin\Debug\Microsoft.Cci.SourceModel.pdb %folder%
xcopy /y  .\Converters\ReflectionImporter\bin\Debug\CodeContracts\Microsoft.Cci.ReflectionImporter.Contracts.dll %folder%
xcopy /y  .\Converters\ReflectionImporter\bin\Debug\CodeContracts\Microsoft.Cci.ReflectionImporter.Contracts.pdb %folder%
xcopy /y  .\Converters\ReflectionImporter\bin\Debug\Microsoft.Cci.MetadataHelper.dll %folder%
xcopy /y  .\Converters\ReflectionImporter\bin\Debug\Microsoft.Cci.MetadataHelper.pdb %folder%
xcopy /y  .\Converters\ReflectionImporter\bin\Debug\Microsoft.Cci.MetadataModel.dll %folder%
xcopy /y  .\Converters\ReflectionImporter\bin\Debug\Microsoft.Cci.MetadataModel.pdb %folder%
xcopy /y  .\Converters\ReflectionImporter\bin\Debug\Microsoft.Cci.ReflectionImporter.dll %folder%
xcopy /y  .\Converters\ReflectionImporter\bin\Debug\Microsoft.Cci.ReflectionImporter.pdb %folder%
xcopy /y  .\CoreObjectModel\AstsProjectedAsCodeModel\bin\Debug\CodeContracts\Microsoft.Cci.AstsProjectedAsCodeModel.Contracts.dll %folder%
xcopy /y  .\CoreObjectModel\AstsProjectedAsCodeModel\bin\Debug\CodeContracts\Microsoft.Cci.AstsProjectedAsCodeModel.Contracts.pdb %folder%
xcopy /y  .\CoreObjectModel\AstsProjectedAsCodeModel\bin\Debug\Microsoft.Cci.AstsProjectedAsCodeModel.dll %folder%
xcopy /y  .\CoreObjectModel\AstsProjectedAsCodeModel\bin\Debug\Microsoft.Cci.AstsProjectedAsCodeModel.pdb %folder%
xcopy /y  .\CoreObjectModel\AstsProjectedAsCodeModel\bin\Debug\Microsoft.Cci.CodeModel.dll %folder%
xcopy /y  .\CoreObjectModel\AstsProjectedAsCodeModel\bin\Debug\Microsoft.Cci.CodeModel.pdb %folder%
xcopy /y  .\CoreObjectModel\AstsProjectedAsCodeModel\bin\Debug\Microsoft.Cci.CodeModelToIL.dll %folder%
xcopy /y  .\CoreObjectModel\AstsProjectedAsCodeModel\bin\Debug\Microsoft.Cci.CodeModelToIL.pdb %folder%
xcopy /y  .\CoreObjectModel\AstsProjectedAsCodeModel\bin\Debug\Microsoft.Cci.ILGenerator.dll %folder%
xcopy /y  .\CoreObjectModel\AstsProjectedAsCodeModel\bin\Debug\Microsoft.Cci.ILGenerator.pdb %folder%
xcopy /y  .\CoreObjectModel\AstsProjectedAsCodeModel\bin\Debug\Microsoft.Cci.MetadataHelper.dll %folder%
xcopy /y  .\CoreObjectModel\AstsProjectedAsCodeModel\bin\Debug\Microsoft.Cci.MetadataHelper.pdb %folder%
xcopy /y  .\CoreObjectModel\AstsProjectedAsCodeModel\bin\Debug\Microsoft.Cci.MetadataModel.dll %folder%
xcopy /y  .\CoreObjectModel\AstsProjectedAsCodeModel\bin\Debug\Microsoft.Cci.MetadataModel.pdb %folder%
xcopy /y  .\CoreObjectModel\AstsProjectedAsCodeModel\bin\Debug\Microsoft.Cci.MutableCodeModel.dll %folder%
xcopy /y  .\CoreObjectModel\AstsProjectedAsCodeModel\bin\Debug\Microsoft.Cci.MutableCodeModel.pdb %folder%
xcopy /y  .\CoreObjectModel\AstsProjectedAsCodeModel\bin\Debug\Microsoft.Cci.MutableMetadataModel.dll %folder%
xcopy /y  .\CoreObjectModel\AstsProjectedAsCodeModel\bin\Debug\Microsoft.Cci.MutableMetadataModel.pdb %folder%
xcopy /y  .\CoreObjectModel\AstsProjectedAsCodeModel\bin\Debug\Microsoft.Cci.SourceModel.dll %folder%
xcopy /y  .\CoreObjectModel\AstsProjectedAsCodeModel\bin\Debug\Microsoft.Cci.SourceModel.pdb %folder%
xcopy /y  .\CoreObjectModel\CodeModel\bin\Debug\CodeContracts\Microsoft.Cci.CodeModel.Contracts.dll %folder%
xcopy /y  .\CoreObjectModel\CodeModel\bin\Debug\CodeContracts\Microsoft.Cci.CodeModel.Contracts.pdb %folder%
xcopy /y  .\CoreObjectModel\CodeModel\bin\Debug\Microsoft.Cci.CodeModel.dll %folder%
xcopy /y  .\CoreObjectModel\CodeModel\bin\Debug\Microsoft.Cci.CodeModel.pdb %folder%
xcopy /y  .\CoreObjectModel\CodeModel\bin\Debug\Microsoft.Cci.MetadataHelper.dll %folder%
xcopy /y  .\CoreObjectModel\CodeModel\bin\Debug\Microsoft.Cci.MetadataHelper.pdb %folder%
xcopy /y  .\CoreObjectModel\CodeModel\bin\Debug\Microsoft.Cci.MetadataModel.dll %folder%
xcopy /y  .\CoreObjectModel\CodeModel\bin\Debug\Microsoft.Cci.MetadataModel.pdb %folder%
xcopy /y  .\CoreObjectModel\CodeModel\bin\Debug\Microsoft.Cci.SourceModel.dll %folder%
xcopy /y  .\CoreObjectModel\CodeModel\bin\Debug\Microsoft.Cci.SourceModel.pdb %folder%
xcopy /y  .\CoreObjectModel\MetadataHelper\bin\Debug\CodeContracts\Microsoft.Cci.MetadataHelper.Contracts.dll %folder%
xcopy /y  .\CoreObjectModel\MetadataHelper\bin\Debug\CodeContracts\Microsoft.Cci.MetadataHelper.Contracts.pdb %folder%
xcopy /y  .\CoreObjectModel\MetadataHelper\bin\Debug\Microsoft.Cci.MetadataHelper.dll %folder%
xcopy /y  .\CoreObjectModel\MetadataHelper\bin\Debug\Microsoft.Cci.MetadataHelper.pdb %folder%
xcopy /y  .\CoreObjectModel\MetadataHelper\bin\Debug\Microsoft.Cci.MetadataModel.dll %folder%
xcopy /y  .\CoreObjectModel\MetadataHelper\bin\Debug\Microsoft.Cci.MetadataModel.pdb %folder%
xcopy /y  .\CoreObjectModel\MetadataModel\bin\Debug\CodeContracts\Microsoft.Cci.MetadataModel.Contracts.dll %folder%
xcopy /y  .\CoreObjectModel\MetadataModel\bin\Debug\CodeContracts\Microsoft.Cci.MetadataModel.Contracts.pdb %folder%
xcopy /y  .\CoreObjectModel\MetadataModel\bin\Debug\Microsoft.Cci.MetadataModel.dll %folder%
xcopy /y  .\CoreObjectModel\MetadataModel\bin\Debug\Microsoft.Cci.MetadataModel.pdb %folder%
xcopy /y  .\CoreObjectModel\MutableCodeModel\bin\Debug\CodeContracts\Microsoft.Cci.MutableCodeModel.Contracts.dll %folder%
xcopy /y  .\CoreObjectModel\MutableCodeModel\bin\Debug\CodeContracts\Microsoft.Cci.MutableCodeModel.Contracts.pdb %folder%
xcopy /y  .\CoreObjectModel\MutableCodeModel\bin\Debug\Microsoft.Cci.CodeModel.dll %folder%
xcopy /y  .\CoreObjectModel\MutableCodeModel\bin\Debug\Microsoft.Cci.CodeModel.pdb %folder%
xcopy /y  .\CoreObjectModel\MutableCodeModel\bin\Debug\Microsoft.Cci.CodeModelToIL.dll %folder%
xcopy /y  .\CoreObjectModel\MutableCodeModel\bin\Debug\Microsoft.Cci.CodeModelToIL.pdb %folder%
xcopy /y  .\CoreObjectModel\MutableCodeModel\bin\Debug\Microsoft.Cci.ILGenerator.dll %folder%
xcopy /y  .\CoreObjectModel\MutableCodeModel\bin\Debug\Microsoft.Cci.ILGenerator.pdb %folder%
xcopy /y  .\CoreObjectModel\MutableCodeModel\bin\Debug\Microsoft.Cci.MetadataHelper.dll %folder%
xcopy /y  .\CoreObjectModel\MutableCodeModel\bin\Debug\Microsoft.Cci.MetadataHelper.pdb %folder%
xcopy /y  .\CoreObjectModel\MutableCodeModel\bin\Debug\Microsoft.Cci.MetadataModel.dll %folder%
xcopy /y  .\CoreObjectModel\MutableCodeModel\bin\Debug\Microsoft.Cci.MetadataModel.pdb %folder%
xcopy /y  .\CoreObjectModel\MutableCodeModel\bin\Debug\Microsoft.Cci.MutableCodeModel.dll %folder%
xcopy /y  .\CoreObjectModel\MutableCodeModel\bin\Debug\Microsoft.Cci.MutableCodeModel.pdb %folder%
xcopy /y  .\CoreObjectModel\MutableCodeModel\bin\Debug\Microsoft.Cci.MutableMetadataModel.dll %folder%
xcopy /y  .\CoreObjectModel\MutableCodeModel\bin\Debug\Microsoft.Cci.MutableMetadataModel.pdb %folder%
xcopy /y  .\CoreObjectModel\MutableCodeModel\bin\Debug\Microsoft.Cci.SourceModel.dll %folder%
xcopy /y  .\CoreObjectModel\MutableCodeModel\bin\Debug\Microsoft.Cci.SourceModel.pdb %folder%
xcopy /y  .\CoreObjectModel\MutableMetadataModel\bin\Debug\CodeContracts\Microsoft.Cci.MutableMetadataModel.Contracts.dll %folder%
xcopy /y  .\CoreObjectModel\MutableMetadataModel\bin\Debug\CodeContracts\Microsoft.Cci.MutableMetadataModel.Contracts.pdb %folder%
xcopy /y  .\CoreObjectModel\MutableMetadataModel\bin\Debug\Microsoft.Cci.MetadataHelper.dll %folder%
xcopy /y  .\CoreObjectModel\MutableMetadataModel\bin\Debug\Microsoft.Cci.MetadataHelper.pdb %folder%
xcopy /y  .\CoreObjectModel\MutableMetadataModel\bin\Debug\Microsoft.Cci.MetadataModel.dll %folder%
xcopy /y  .\CoreObjectModel\MutableMetadataModel\bin\Debug\Microsoft.Cci.MetadataModel.pdb %folder%
xcopy /y  .\CoreObjectModel\MutableMetadataModel\bin\Debug\Microsoft.Cci.MutableMetadataModel.dll %folder%
xcopy /y  .\CoreObjectModel\MutableMetadataModel\bin\Debug\Microsoft.Cci.MutableMetadataModel.pdb %folder%
xcopy /y  .\CoreObjectModel\SourceModel\bin\Debug\CodeContracts\Microsoft.Cci.SourceModel.Contracts.dll %folder%
xcopy /y  .\CoreObjectModel\SourceModel\bin\Debug\CodeContracts\Microsoft.Cci.SourceModel.Contracts.pdb %folder%
xcopy /y  .\CoreObjectModel\SourceModel\bin\Debug\Microsoft.Cci.MetadataHelper.dll %folder%
xcopy /y  .\CoreObjectModel\SourceModel\bin\Debug\Microsoft.Cci.MetadataHelper.pdb %folder%
xcopy /y  .\CoreObjectModel\SourceModel\bin\Debug\Microsoft.Cci.MetadataModel.dll %folder%
xcopy /y  .\CoreObjectModel\SourceModel\bin\Debug\Microsoft.Cci.MetadataModel.pdb %folder%
xcopy /y  .\CoreObjectModel\SourceModel\bin\Debug\Microsoft.Cci.SourceModel.dll %folder%
xcopy /y  .\CoreObjectModel\SourceModel\bin\Debug\Microsoft.Cci.SourceModel.pdb %folder%
xcopy /y  .\PDBReaderAndWriter\PdbReader\bin\Debug\CodeContracts\Microsoft.Cci.pdb %folder%Reader.Contracts.dll %folder%
xcopy /y  .\PDBReaderAndWriter\PdbReader\bin\Debug\CodeContracts\Microsoft.Cci.pdb %folder%Reader.Contracts.pdb %folder%
xcopy /y  .\PDBReaderAndWriter\PdbReader\bin\Debug\Microsoft.Cci.MetadataHelper.dll %folder%
xcopy /y  .\PDBReaderAndWriter\PdbReader\bin\Debug\Microsoft.Cci.MetadataHelper.pdb %folder%
xcopy /y  .\PDBReaderAndWriter\PdbReader\bin\Debug\Microsoft.Cci.MetadataModel.dll %folder%
xcopy /y  .\PDBReaderAndWriter\PdbReader\bin\Debug\Microsoft.Cci.MetadataModel.pdb %folder%
xcopy /y  .\PDBReaderAndWriter\PdbReader\bin\Debug\Microsoft.Cci.pdb %folder%Reader.dll %folder%
xcopy /y  .\PDBReaderAndWriter\PdbReader\bin\Debug\Microsoft.Cci.pdb %folder%Reader.pdb %folder%
xcopy /y  .\PDBReaderAndWriter\PdbReader\bin\Debug\Microsoft.Cci.PeReader.dll %folder%
xcopy /y  .\PDBReaderAndWriter\PdbReader\bin\Debug\Microsoft.Cci.PeReader.pdb %folder%
xcopy /y  .\PDBReaderAndWriter\PdbReader\bin\Debug\Microsoft.Cci.SourceModel.dll %folder%
xcopy /y  .\PDBReaderAndWriter\PdbReader\bin\Debug\Microsoft.Cci.SourceModel.pdb %folder%
xcopy /y  .\PDBReaderAndWriter\PdbWriter\bin\Debug\CodeContracts\Microsoft.Cci.pdb %folder%Writer.Contracts.dll %folder%
xcopy /y  .\PDBReaderAndWriter\PdbWriter\bin\Debug\CodeContracts\Microsoft.Cci.pdb %folder%Writer.Contracts.pdb %folder%
xcopy /y  .\PDBReaderAndWriter\PdbWriter\bin\Debug\Microsoft.Cci.MetadataHelper.dll %folder%
xcopy /y  .\PDBReaderAndWriter\PdbWriter\bin\Debug\Microsoft.Cci.MetadataHelper.pdb %folder%
xcopy /y  .\PDBReaderAndWriter\PdbWriter\bin\Debug\Microsoft.Cci.MetadataModel.dll %folder%
xcopy /y  .\PDBReaderAndWriter\PdbWriter\bin\Debug\Microsoft.Cci.MetadataModel.pdb %folder%
xcopy /y  .\PDBReaderAndWriter\PdbWriter\bin\Debug\Microsoft.Cci.pdb %folder%Writer.dll %folder%
xcopy /y  .\PDBReaderAndWriter\PdbWriter\bin\Debug\Microsoft.Cci.pdb %folder%Writer.pdb %folder%
xcopy /y  .\PDBReaderAndWriter\PdbWriter\bin\Debug\Microsoft.Cci.PeWriter.dll %folder%
xcopy /y  .\PDBReaderAndWriter\PdbWriter\bin\Debug\Microsoft.Cci.PeWriter.pdb %folder%
xcopy /y  .\PDBReaderAndWriter\PdbWriter\bin\Debug\Microsoft.Cci.SourceModel.dll %folder%
xcopy /y  .\PDBReaderAndWriter\PdbWriter\bin\Debug\Microsoft.Cci.SourceModel.pdb %folder%
xcopy /y  .\PEReaderAndWriter\PEReader\bin\Debug\CodeContracts\Microsoft.Cci.PeReader.Contracts.dll %folder%
xcopy /y  .\PEReaderAndWriter\PEReader\bin\Debug\CodeContracts\Microsoft.Cci.PeReader.Contracts.pdb %folder%
xcopy /y  .\PEReaderAndWriter\PEReader\bin\Debug\Microsoft.Cci.MetadataHelper.dll %folder%
xcopy /y  .\PEReaderAndWriter\PEReader\bin\Debug\Microsoft.Cci.MetadataHelper.pdb %folder%
xcopy /y  .\PEReaderAndWriter\PEReader\bin\Debug\Microsoft.Cci.MetadataModel.dll %folder%
xcopy /y  .\PEReaderAndWriter\PEReader\bin\Debug\Microsoft.Cci.MetadataModel.pdb %folder%
xcopy /y  .\PEReaderAndWriter\PEReader\bin\Debug\Microsoft.Cci.PeReader.dll %folder%
xcopy /y  .\PEReaderAndWriter\PEReader\bin\Debug\Microsoft.Cci.PeReader.pdb %folder%
xcopy /y  .\PEReaderAndWriter\PEWriter\bin\Debug\CodeContracts\Microsoft.Cci.PeWriter.Contracts.dll %folder%
xcopy /y  .\PEReaderAndWriter\PEWriter\bin\Debug\CodeContracts\Microsoft.Cci.PeWriter.Contracts.pdb %folder%
xcopy /y  .\PEReaderAndWriter\PEWriter\bin\Debug\Microsoft.Cci.MetadataHelper.dll %folder%
xcopy /y  .\PEReaderAndWriter\PEWriter\bin\Debug\Microsoft.Cci.MetadataHelper.pdb %folder%
xcopy /y  .\PEReaderAndWriter\PEWriter\bin\Debug\Microsoft.Cci.MetadataModel.dll %folder%
xcopy /y  .\PEReaderAndWriter\PEWriter\bin\Debug\Microsoft.Cci.MetadataModel.pdb %folder%
xcopy /y  .\PEReaderAndWriter\PEWriter\bin\Debug\Microsoft.Cci.PeWriter.dll %folder%
xcopy /y  .\PEReaderAndWriter\PEWriter\bin\Debug\Microsoft.Cci.PeWriter.pdb %folder%
xcopy /y  .\PEReaderAndWriter\PEWriter\bin\Debug\Microsoft.Cci.SourceModel.dll %folder%
xcopy /y  .\PEReaderAndWriter\PEWriter\bin\Debug\Microsoft.Cci.SourceModel.pdb %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\AsmMeta.pdb %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\CodeContracts\AsmMeta.Contracts.dll %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\CodeContracts\AsmMeta.Contracts.pdb %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.Analysis.ControlAndDataFlowGraph.dll %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.Analysis.ControlAndDataFlowGraph.pdb %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.CodeModel.dll %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.CodeModel.pdb %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.CodeModelToIL.dll %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.CodeModelToIL.pdb %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.ContractExtractor.dll %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.ContractExtractor.pdb %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.CSharpSourceEmitter.dll %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.CSharpSourceEmitter.pdb %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.ILGenerator.dll %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.ILGenerator.pdb %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.MetadataHelper.dll %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.MetadataHelper.pdb %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.MetadataModel.dll %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.MetadataModel.pdb %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.MutableCodeModel.dll %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.MutableCodeModel.pdb %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.MutableMetadataModel.dll %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.MutableMetadataModel.pdb %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.NewILToCodeModel.dll %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.NewILToCodeModel.pdb %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.pdb %folder%Reader.dll %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.pdb %folder%Reader.pdb %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.pdb %folder%Writer.dll %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.pdb %folder%Writer.pdb %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.PeReader.dll %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.PeReader.pdb %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.PeWriter.dll %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.PeWriter.pdb %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.SourceModel.dll %folder%
xcopy /y  .\Samples\AsmMeta\bin\Debug\Microsoft.Cci.SourceModel.pdb %folder%
xcopy /y  .\SourceEmitters\CSharpSourceEmitter\bin\Debug\CodeContracts\Microsoft.Cci.CSharpSourceEmitter.Contracts.dll %folder%
xcopy /y  .\SourceEmitters\CSharpSourceEmitter\bin\Debug\CodeContracts\Microsoft.Cci.CSharpSourceEmitter.Contracts.pdb %folder%
xcopy /y  .\SourceEmitters\CSharpSourceEmitter\bin\Debug\Microsoft.Cci.CodeModel.dll %folder%
xcopy /y  .\SourceEmitters\CSharpSourceEmitter\bin\Debug\Microsoft.Cci.CodeModel.pdb %folder%
xcopy /y  .\SourceEmitters\CSharpSourceEmitter\bin\Debug\Microsoft.Cci.CSharpSourceEmitter.dll %folder%
xcopy /y  .\SourceEmitters\CSharpSourceEmitter\bin\Debug\Microsoft.Cci.CSharpSourceEmitter.pdb %folder%
xcopy /y  .\SourceEmitters\CSharpSourceEmitter\bin\Debug\Microsoft.Cci.MetadataHelper.dll %folder%
xcopy /y  .\SourceEmitters\CSharpSourceEmitter\bin\Debug\Microsoft.Cci.MetadataHelper.pdb %folder%
xcopy /y  .\SourceEmitters\CSharpSourceEmitter\bin\Debug\Microsoft.Cci.MetadataModel.dll %folder%
xcopy /y  .\SourceEmitters\CSharpSourceEmitter\bin\Debug\Microsoft.Cci.MetadataModel.pdb %folder%
xcopy /y  .\SourceEmitters\CSharpSourceEmitter\bin\Debug\Microsoft.Cci.SourceModel.dll %folder%
xcopy /y  .\SourceEmitters\CSharpSourceEmitter\bin\Debug\Microsoft.Cci.SourceModel.pdb %folder%
xcopy /y  .\SourceEmitters\SourceEmitter\bin\Debug\CodeContracts\Microsoft.Cci.SourceEmitter.Contracts.dll %folder%
xcopy /y  .\SourceEmitters\SourceEmitter\bin\Debug\CodeContracts\Microsoft.Cci.SourceEmitter.Contracts.pdb %folder%
xcopy /y  .\SourceEmitters\SourceEmitter\bin\Debug\Microsoft.Cci.SourceEmitter.dll %folder%
xcopy /y  .\SourceEmitters\SourceEmitter\bin\Debug\Microsoft.Cci.SourceEmitter.pdb %folder%
xcopy /y  .\SourceEmitters\VB\VBSourceEmitter\bin\Debug\CodeContracts\Microsoft.Cci.VBSourceEmitter.Contracts.dll %folder%
xcopy /y  .\SourceEmitters\VB\VBSourceEmitter\bin\Debug\CodeContracts\Microsoft.Cci.VBSourceEmitter.Contracts.pdb %folder%
xcopy /y  .\SourceEmitters\VB\VBSourceEmitter\bin\Debug\Microsoft.Cci.AstsProjectedAsCodeModel.dll %folder%
xcopy /y  .\SourceEmitters\VB\VBSourceEmitter\bin\Debug\Microsoft.Cci.AstsProjectedAsCodeModel.pdb %folder%
xcopy /y  .\SourceEmitters\VB\VBSourceEmitter\bin\Debug\Microsoft.Cci.CodeModel.dll %folder%
xcopy /y  .\SourceEmitters\VB\VBSourceEmitter\bin\Debug\Microsoft.Cci.CodeModel.pdb %folder%
xcopy /y  .\SourceEmitters\VB\VBSourceEmitter\bin\Debug\Microsoft.Cci.CodeModelToIL.dll %folder%
xcopy /y  .\SourceEmitters\VB\VBSourceEmitter\bin\Debug\Microsoft.Cci.CodeModelToIL.pdb %folder%
xcopy /y  .\SourceEmitters\VB\VBSourceEmitter\bin\Debug\Microsoft.Cci.ILGenerator.dll %folder%
xcopy /y  .\SourceEmitters\VB\VBSourceEmitter\bin\Debug\Microsoft.Cci.ILGenerator.pdb %folder%
xcopy /y  .\SourceEmitters\VB\VBSourceEmitter\bin\Debug\Microsoft.Cci.MetadataHelper.dll %folder%
xcopy /y  .\SourceEmitters\VB\VBSourceEmitter\bin\Debug\Microsoft.Cci.MetadataHelper.pdb %folder%
xcopy /y  .\SourceEmitters\VB\VBSourceEmitter\bin\Debug\Microsoft.Cci.MetadataModel.dll %folder%
xcopy /y  .\SourceEmitters\VB\VBSourceEmitter\bin\Debug\Microsoft.Cci.MetadataModel.pdb %folder%
xcopy /y  .\SourceEmitters\VB\VBSourceEmitter\bin\Debug\Microsoft.Cci.MutableCodeModel.dll %folder%
xcopy /y  .\SourceEmitters\VB\VBSourceEmitter\bin\Debug\Microsoft.Cci.MutableCodeModel.pdb %folder%
xcopy /y  .\SourceEmitters\VB\VBSourceEmitter\bin\Debug\Microsoft.Cci.MutableMetadataModel.dll %folder%
xcopy /y  .\SourceEmitters\VB\VBSourceEmitter\bin\Debug\Microsoft.Cci.MutableMetadataModel.pdb %folder%
xcopy /y  .\SourceEmitters\VB\VBSourceEmitter\bin\Debug\Microsoft.Cci.SourceModel.dll %folder%
xcopy /y  .\SourceEmitters\VB\VBSourceEmitter\bin\Debug\Microsoft.Cci.SourceModel.pdb %folder%
xcopy /y  .\SourceEmitters\VB\VBSourceEmitter\bin\Debug\Microsoft.Cci.VBSourceEmitter.dll %folder%
xcopy /y  .\SourceEmitters\VB\VBSourceEmitter\bin\Debug\Microsoft.Cci.VBSourceEmitter.pdb %folder%
pause